import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./(components)/navbar";
import SessionProviderWrapper from "@/context/provider";
import NavbarAgain from "@/components/ui/navbar-menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Industry Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session: never;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProviderWrapper session={session}>
          {/* <NavBar /> */}
          <NavbarAgain />
          {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
